baseURL: "https://aubreypwd.github.io/"
languageCode: "en-us"
title: "aubreypwd"
theme: "anubis"
paginate: 1000
# disqusShortname: yourdiscussshortname
# googleAnalytics: UA-123-45
enableRobotsTXT: true
menu:
  main:
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 0

params:
  author: "Aubrey Portwood"
  description: "WordPress Developer, Stoic"
  images:
    # - images/og-featured.png # relative path to "static" directory
  customCSS:
    # - css/my.css # relative path to "static" directory
  customJS:
    # - js/main.js # relative path to "static" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: dark-without-switcher

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
