baseURL: 'https://aubreypwd.com'
title: Aubrey Portwood
languageCode: en-us
theme: hello-friend
# PygmentsCodeFences: true
# PygmentsStyle: monokai
paginate: 5
rssLimit: 500
copyright: 'Copyright &copy; Aubrey Portwood / <a href="/index.xml"><i class="im im-radio"></i> RSS</a> / Powered by <a href="https://https://gohugo.io/">hugo</a> &amp; <a href="https://github.com/panr/hugo-theme-hello-friend" target="_blank">hello-friend</a>'
enableRobotsTXT: true
preserveTaxonomyNames: true
enableGitInfo: true
enableEmoji: true
# enableMissingTranslationPlaceholders: false
# disableRSS: false
# disableSitemap: false
# disable404: true
# disableHugoGeneratorInject: false
permalinks:
  posts: ':filename'
  archive: ':filename'
author:
  name: Aubrey Portwood
blackfriday:
  hrefTargetBlank: true
taxonomies:
  tag: tags
params:
  subtitle: WordPress Engineer | Stoic
  dateform: 'Jan 2, 2006'
  dateformShort: Jan 2
  dateformNum: '2006-01-02'
  dateformNumTime: '2006-01-02 15:04 -0700'
  newerPosts: "Previous"
  olderPosts: "Next"
  keywords: 'aubrey,portwood,aubreypwd,wordpress,stoic,stoicism,developer'
  # disableReadOtherPosts: true
  # justifyContent: false
  defaultTheme: dark
  logo:
    logoText: "~/aubreypwd"
    logoHomeLink: /
    logoCursorAnimate: 1s
languages:
  en:
    weight: 1
menu:
  main:
    - identifier: code
      name: "Github"
      url: https://github.com/aubreypwd
    - identifier: linkedin
      name: "LinkedIn"
      url: https://linkedin.com/in/aubreypwd
    - identifier: tweets
      name: "Tweets"
      url: https://twitter.com/aubreypwd    
    - identifier: stoicism
      name: "Stoicism"
      url: /tags/stoicism
markup:
  goldmark:
    renderer:
      unsafe: true
